CREATE TABLE IF NOT EXISTS urls (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  url TEXT UNIQUE NOT NULL,
  first_encountered DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_checked DATETIME DEFAULT NULL,
  last_saved DATETIME DEFAULT NULL,
  is_monitored BOOLEAN NOT NULL DEFAULT 0,
  version INTEGER NOT NULL DEFAULT 1 CHECK (version >= 0)
);
